cursor #f0f0f0
cursor_text_color #c9b8d9

foreground            #f0f0f0
background            #09070d
selection_foreground  #1e1e00
selection_background  #92eda7
url_color             #b8a8f0

color0   #130f1a
color1   #ff7290
color2   #78f090
color3   #ffd972
color4   #a491e3
color5   #3f316f
color6   #b8a8f0
color7   #f0ecfc
color8   #92909c
color9   #ff9fb3
color10  #a5ffb7
color11  #ffe7a5
color12  #ccbdff
color13  #d5c9ff
color14  #e4dcff
color15  #faf8ff
