cursor #d7e6e2
cursor_text_color #bbcac6

foreground            #d7e6e2
background            #091614
selection_foreground  #00363a
selection_background  #a0cfd3
url_color             #00deca

color0   #091614
color1   #ff5900
color2   #00de10
color3   #ffeb00
color4   #00d2bf
color5   #00665d
color6   #00deca
color7   #cde9e6
color8   #7a908e
color9   #ff823f
color10  #4cff59
color11  #fff14c
color12  #24f4e1
color13  #4cffee
color14  #8cfff4
color15  #f2fffd
